target-version = "py312"

line-length = 200
indent-width = 4

[lint]
select = [
    "ALL",
]

ignore = [
    "ERA001", # disable commented code detection
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "ARG001",
    "N818",
]

[lint.pylint]
max-args = 10

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25